import{a as B,S as I,i as n}from"./assets/vendor-lDhL-8I6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function m(o,t){return(await B.get("https://pixabay.com/api/",{params:{key:"49809160-ecb9db209c3e158eb7196d46c",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const q=new I(".gallery a",{captionsData:"alt",captionDelay:250}),p=document.querySelector(".gallery");function h(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:i,comments:P,downloads:v})=>`<li class="gallery-item">
                    <a href="${s}">
                        <img class="gallery-image" src="${a}" alt="${e}" />
                        <div class='info'>
                            <p><b>likes</b> ${r}</p>
                            <p><b>views</b> ${i}</p>
                            <p><b>comments</b> ${P}</p>
                            <p><b>downloads</b> ${v}</p>
                        </div>
                    </a>
                </li>`).join("");p.insertAdjacentHTML("beforeend",t),q.refresh()}function w(){p.innerHTML=""}const g=document.querySelector(".div-loader");function y(){g.classList.remove("hidden")}function b(){g.classList.add("hidden")}const L=document.querySelector(".btn-load-more");function A(){L.classList.remove("hidden")}function f(){L.classList.add("hidden")}const d=document.querySelector(".form");let c=1,u=1,l="";d.addEventListener("submit",async o=>{if(o.preventDefault(),l=d.elements["search-text"].value,w(),l===""){n.error({message:"Please enter a search query!",position:"topRight"});return}y();try{const t=await m(l,c);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(t.hits),u=Math.ceil(t.totalHits/15),u>1&&A()}catch{n.error({message:"❌ Error fetching images from PIXABAY`",position:"topRight"})}finally{b()}d.reset()});const S=document.querySelector(".btn-load-more");S.addEventListener("click",_);async function _(){c+=1,f(),y();try{const o=await m(l,c);h(o.hits);const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),c>=u?(f(),n.info({message:"You have reached the end of search results"})):A()}catch{n.error({message:"❌ Error fetching images from PIXABAY`",position:"topRight"})}finally{b()}}
//# sourceMappingURL=index.js.map
