import{a as P,S as v,i as a}from"./assets/vendor-lDhL-8I6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function m(o,r){return(await P.get("https://pixabay.com/api/",{params:{key:"49809160-ecb9db209c3e158eb7196d46c",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const B=new v(".gallery a",{captionsData:"alt",captionDelay:250}),f=document.querySelector(".gallery");function p(o){const r=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:n,comments:L,downloads:A})=>`<li class="gallery-item">
                    <a href="${i}">
                        <img class="gallery-image" src="${s}" alt="${e}" />
                        <div class='info'>
                            <p><b>likes</b> ${t}</p>
                            <p><b>views</b> ${n}</p>
                            <p><b>comments</b> ${L}</p>
                            <p><b>downloads</b> ${A}</p>
                        </div>
                    </a>
                </li>`).join("");f.insertAdjacentHTML("beforeend",r),B.refresh()}function q(){f.innerHTML=""}const h=document.querySelector(".div-loader");function g(){h.classList.remove("hidden")}function I(){h.classList.add("hidden")}const y=document.querySelector(".btn-load-more");function b(){y.classList.remove("hidden")}function u(){y.classList.add("hidden")}const l=document.querySelector(".form");let c=1,d=1;l.addEventListener("submit",async o=>{o.preventDefault();const r=l.elements["search-text"].value;if(q(),r===""){a.error({message:"Please enter a search query!",position:"topRight"});return}g();try{const s=await m(r,c);if(s.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(s.hits),d=Math.ceil(s.totalHits/15),d>1&&b()}catch{a.error({message:"❌ Error fetching images from PIXABAY`",position:"topRight"})}finally{I()}l.reset()});const w=document.querySelector(".btn-load-more");w.addEventListener("click",S);async function S(){c+=1,u(),g();try{const o=await m(query,c);p(o.hits);const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),c>=d?(u(),a.info({message:"You have reached the end of search results"})):b()}catch{a.error({message:"❌ Error fetching images from PIXABAY`",position:"topRight"})}}
//# sourceMappingURL=index.js.map
