import{a as m,i as n,S as p}from"./assets/vendor-lDhL-8I6.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function g(i){const o="49782329-6d8bd30771b2969fa2e08a84b",a="https://pixabay.com/api/",r={image_type:"photo",orientation:"horizontal",safesearch:"true"};return m.get(`${a}?key=${o}&q=${i}&image_type=${r.image_type}&orientation=${r.orientation}&safesearch=${r.safesearch}`).then(e=>e.data).catch(e=>{n.error({message:"❌ Error fetching images from PIXABAY",position:"topRight"})})}const h=new p(".gallery a",{captionsData:"alt",captionDelay:250}),l=document.querySelector(".gallery");function y(i){const o=i.map(({webformatURL:a,largeImageURL:r,tags:e,likes:t,views:s,comments:f,downloads:d})=>`<li class="gallery-item">
                    <a href="${r}">
                        <img class="gallery-image" src="${a}" alt="${e}" />
                        <div class='info'>
                            <p><b>likes</b> ${t}</p>
                            <p><b>views</b> ${s}</p>
                            <p><b>comments</b> ${f}</p>
                            <p><b>downloads</b> ${d}</p>
                        </div>
                    </a>
                </li>`).join("");l.innerHTML=o,h.refresh()}function b(){l.innerHTML=""}const u=document.querySelector(".loader");function A(){u.classList.remove("hidden")}function L(){u.classList.add("hidden")}const c=document.querySelector(".form");c.addEventListener("submit",i=>{i.preventDefault();const o=c.elements["search-text"].value;if(b(),o===""){n.error({message:"Please enter a search query!",position:"topRight"});return}A(),g(o).then(r=>{if(r.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(r.hits)}).catch(()=>{n.error({message:"❌ Error fetching images from PIXABAY`",position:"topRight"})}).finally(()=>{L()}),c.reset()});
//# sourceMappingURL=index.js.map
